### ISSUE TITLE
Crash in `getArgument`

### ISSUE THREAD

**Issue by AlexJWayne** [alphamikle/nest_transact#1]
I have a service that depends on a service that uses the HttpModule for external API communication. This caused a problem with this library.

The problem is that the repository detection is a bit naive. Currently it decides the dependency is a Repository if the it is a string, but other dependencies may be string at this point as well, like the `HttpModule`.

```typescript
  private getArgument(param: string | ClassType, manager: EntityManager): any {
    let argument: Repository<any>;
    const id = typeof param === 'string' ? param : param.name;
    if (this.cache.has(id)) {
      return this.cache.get(id);
    }
    if (typeof param === 'string') {
      const repository: Repository<any> = this.moduleRef.get(param, { strict: false });

      const entity: any = repository.metadata.target; // crash! target is not a property of undefined

      argument = manager.getRepository(entity);
    } else {
      argument = this.findArgumentsForProvider(param as ClassType, manager);
    }
    this.cache.set(id, argument);
    return argument;
  }
```

I was able to fix this by adding a `instanceof Repository` check, to make sure that we have an actual TypeORM before we access it's metadata that might not be there.

```typescript
   private getArgument(param: string | ClassType, manager: EntityManager): any {
    let argument: Repository<any>
    const id = typeof param === 'string' ? param : param.name

    if (this.cache.has(id)) {
      return this.cache.get(id)
    }

    if (typeof param === 'string') {
      // Fetch the depedency.
      const depedency: Repository<any> = this.moduleRef.get(param, { strict: false })

      if (depedency instanceof Repository) {
        // If the dependency is a repository, make a new repository with the desired transaction manager.
        const entity: any = depedency.metadata.target
        argument = manager.getRepository(entity)
      } else {
        // The dependency is not a repository, use it directly.
        argument = depedency
      }
    } else {
      argument = this.findArgumentsForProvider(param as ClassType, manager)
    }
    this.cache.set(id, argument)
    return argument
  }
```

And now I believe it seems to working as intended.

Thanks for this code. It's an elegant solution to a tricky problem and this has been super helpful!

**Comment by alphamikle** [comment]
Hello, @AlexJWayne! Thank you for this fix, I will add it on this week necessarily

**Comment by alphamikle** [comment]
Hello, @AlexJWayne! All is done! Version 1.0.3 contains your fix. Thank you!

**Comment by alphamikle** [comment]
Hello, @AlexJWayne! Version 1.0.3 had broked transaction logic (usual repos was created with the usual manager, not transaction), because of this I add some fixes and additional features. The actual version is 1.1.2, please use it.
