### ISSUE TITLE
QUESTION: Can I use this lib the same way with GrapqhQL resolvers instead of REST controllers?

### ISSUE THREAD

**Issue by Gleb-Gaiduk** [alphamikle/nest_transact#10]
QUESTION: Can I use this lib the same way with GrapqhQL resolvers instead of REST controllers?

**Comment by alphamikle** [comment]
@Gleb-Gaiduk, to be honest - I don't use it with resolvers, but all which you need to use - the `connection` class and  `TransactionFor<T>` service, which will run in a transaction. If your resolver is like a controller and you can inject the `connection` in its constructor, there is no one reason why you can't use this library.
