### ISSUE TITLE
nest-transact doensn't seem to work well with custom repository

### ISSUE THREAD

**Issue by puroong** [alphamikle/nest_transact#2]
Hi, when I try to use it with custom repostiories, I get error saying cannot get undefined of `whichever method I tried to call with custom repository`

I decorated my custom repository with @EntityRepository and  imported with TypeOrmModule.forFeature in my module where I declared custom repository

Is there anything more I should do to make it work?

I made repository for reproducing errors [here](https://github.com/puroong/nest-transact-with-custom-repository)

**Comment by alphamikle** [comment]
Hello! I'll figure out what's the reason of this problem in the next weekends.

**Comment by moulinraphael** [comment]
I very interested about this issue as well :)

**Comment by moulinraphael** [comment]
In `getArgument` 

```
    if (typeof param === 'string') {
      ...
    } else {
      try {
        argument = manager.getCustomRepository(param);
      } catch (e) {
        argument = this.findArgumentsForProvider(param as ClassType, manager);
      }
    }
  ```

**Comment by alphamikle** [comment]
Hello, @moulinraphael! Version 1.1.2 has the possibility to using custom repositories and some additions too. Enjoy your use! 😃
